### ISSUE TITLE
possible salvagable code

### ISSUE THREAD

**Issue by richfitz** [r-lib/filelock#12]
I had a shot at this a while ago:

https://github.com/richfitz/seagull

works well cross platforms but terribly on SMB shares unfortunately.  There may or may not be useful things in there for your package to salvage

**Comment by gaborcsardi** [comment]
Oh, cool, I did not know this one!

**Comment by gaborcsardi** [comment]
Thanks, I like `with_flock`, I'll implement sg similar. I think the (lack of) polling is superior in `filelock`, that's the main difference between the packages, apart from implementation details.
