### ISSUE TITLE
Locks does not seem to be not inherited by child processes created using fork on Linux

### ISSUE THREAD

**Issue by adamryczkowski** [r-lib/filelock#22]
The code below
```
l<-filelock::lock('/tmp/mylock', TRUE)
j<-parallel::mcparallel({l<-filelock::lock('/tmp/mylock', TRUE)}) #Spawn a forked thread that attempts to acquire the lock as well
parallel::mccollect(j) #This command should hang forever, because our thread has already got the exclusive lock on the /tmp/mylock and has not released it yet.
filelock::unlock(l)
```
Should hang forever, while it does not. If I run line `2` and `3` on the separate R process, it waits until I execute `#4`, just as it should. 

Are you sure the child processes do not inherit the locks? It seems they do.

**Comment by gaborcsardi** [comment]
fork without exec is not supported.

**Comment by gaborcsardi** [comment]
Also, there is basically no way to support this, AFAIK, even if I wanted to.

**Comment by adamryczkowski** [comment]
Are you able to suggest a walkaround? I need to occasionally spawn a background job in R that inherits a large variable without copying it to serialize it to disk.

**Comment by gaborcsardi** [comment]
There is no workaround with filelock. `fork()` always inherits all file descriptors, it is `exec*()` that will close them in the child process.

You can't use filelock for this.
