### ISSUE TITLE
filelock error when using drake

### ISSUE THREAD

**Issue by mattwarkentin** [r-lib/filelock#26]
Hi @gaborcsardi,

I am running into an issue when trying to use the `{drake}` package and it seems to be `filelock` related. The `filelock` error seems to be holding my drake project hostage, so to speak. I keep running into this error:
```
Error in filelock::lock(private$lock_file) : 
  Cannot lock file: '/Matt/.drake/drake/history/lock': Operation not supported
Error in filelock::unlock(lock) : 
  VECTOR_ELT() can only be applied to a 'list', not a 'closure'
```

I really don't know enough about how `filelock` is used internally for `drake`, but I have worked with @wlandau to try and get to the bottom of it by running different bits of code to rule-in and out some issues. All of that can be found here wlandau/drake#1280

I am happy to continue to do whatever I can to help work toward a solution. Thanks for your help.

**Comment by wlandau** [comment]
Thanks for posting. Would you share the same reprex and lock file you posted to drake's issue tracker?

**Comment by mattwarkentin** [comment]
Here is a zip file from my drake project containing the lock file:
https://github.com/ropensci/drake/files/4815500/history.zip

Here is a minimal example:
```r
library(filelock)
lock <- lock(".drake/drake/history/lock")
unlock(lock)
```
```
Error in lock(".drake/drake/history/lock") : 
  Cannot lock file: '/Volumes/hung_lab/shared/Matt/deep-learning/.drake/drake/history/lock': Operation not supported
Error in unlock(lock) : 
  VECTOR_ELT() can only be applied to a 'list', not a 'closure'
```

**Comment by gaborcsardi** [comment]
Well, sadly, that is not a reprex. I obviously do not have a `.drake/drake/history/lock` file.

**Comment by mattwarkentin** [comment]
You do if you download the zip file I also attached!

**Comment by gaborcsardi** [comment]
But I suspect that you are trying to create a lock file on some shared file system, and many of these, e.g. NFS, do not support locks.

**Comment by mattwarkentin** [comment]
It is the network drive at my hospital, so I would assumed that is a shared file system as you describe. I am not sure what NFS is.

**Comment by gaborcsardi** [comment]
https://en.wikipedia.org/wiki/Network_File_System

If this is macOS, and you type `mount` in a terminal, it will tell you the type of the file system. But it does not really matter. If you can use `lock()` in other directories, but cannot use locks on this file system, then based on the error message, the file system does not support locking.

A workaround would be to configure drake to store the lock files somewhere else, if that's possible.

**Comment by mattwarkentin** [comment]
For posterity, when running `mount` in the terminal
```
<<redcated info for mounted volume path>> (smbfs, nodev, nosuid, mounted by matt)
```
Hope this is helpful, @wlandau

**Comment by gaborcsardi** [comment]
Interesting, in theory SMBFS supports locking, AFAIK. In any case, being able to configure a custom directory for lock files is a good idea in general.

**Comment by mattwarkentin** [comment]
I don't know enough about this stuff, so I can't really offer much insight. But running
```
library(filelock)
lock <- lock("/Volumes/mounted_drive/foo")
unlock(lock)
```

**Comment by wlandau** [comment]
Thanks for explaining, @gaborcsardi. I think I can solve this for `drake` via https://github.com/wlandau/txtq/issues/18.

**Comment by wlandau** [comment]
And @mattwarkentin, thanks for https://github.com/r-lib/filelock/issues/26#issuecomment-647806782. That makes it clear we need https://github.com/wlandau/txtq/issues/18.

**Comment by wlandau** [comment]
Would you try 2ffd42af9d9d14f8f1e9482eee03bc24bfbdbb7b? It should be fixed now because I made `drake` avoid file locking altogether (via an update I just made to `txtq`).

**Comment by pydupont** [comment]
It works. Thanks for your work!
