### ISSUE TITLE
improve error reporting when unlock() given invalid object

### ISSUE THREAD

**Issue by kevinushey** [r-lib/filelock#31]
E.g. by mistake, I wrote:

```
file <- tempfile("lockfile-")
writeLines("Hello, world!", con = file)
lock <- filelock::lock(file, exclusive = FALSE)
filelock::unlock(file)
```

and got the error:

```
> filelock::unlock(file)
Error in filelock::unlock(file) : 
  VECTOR_ELT() can only be applied to a 'list', not a 'character'
```

Should `filelock::unlock()` validate that its argument is a proper lock object?

**Comment by gaborcsardi** [comment]
Maybe, IDK. This is a pretty low level package, so I am not too worried about this.

**Comment by gaborcsardi** [comment]
Looks like `lock()` is checking arguments, so yeah, `unlock()` should as well.
