### ISSUE TITLE
No lock file.

### ISSUE THREAD

**Issue by ZheFrench** [r-lib/filelock#39]
Got this error saying no lock file.

https://github.com/Bioconductor/BiocFileCache/blob/master/R/sql.R

This happen due to the call to lock.

It's working on my ubuntu desktop, and in a container but not on the server of my institute.

I  was wondering if this is due to filesystem specificity of my server ? How to know is file locking is available etc...

```
Error in lock(.sql_lock_path(dbfile), exclusive = FALSE) :
  Cannot lock file: '/home/villemin/.cache/biomaRt/BiocFileCache.sqlite.LOCK': No lock file
Appels : biomartCacheInfo ... tryCatch -> tryCatchList -> .sql_connect_RW -> lock
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'conn' in selecting a method for function 'dbDisconnect': object 'info' not found
Calls: <Anonymous> ... .sql_disconnect -> dbDisconnect -> .handleSimpleError -> h
Execution halted
```

`nfsstat -m` told me that is nfs version 3 and local_lock should indicate that lock will not work right ?
`mountvers=3 local_lock=none,
`

**Comment by gaborcsardi** [comment]
I think so, yeah. The locks file needs to be put somewhere else, in this case, e.g. `tempdir()` is usually not on a shared file system.
