### ISSUE TITLE
arm64 support, and an arm64 installation candidate on conda-forge

### ISSUE THREAD

**Issue by grisaitis** [r-lib/filelock#41]
my question is two-fold:
- does this package support arm64 platforms?
- what would it take to add an arm64 installation candidate on conda-forge?

asking because i have a macbook with an arm64 processor. i am unable to `conda install -c conda-forge r-filelock` on my machine because there is no installation candidate. further upstream, my goal is to install `pak`, which requires `filelock`.

**Comment by gaborcsardi** [comment]
All CRAN packages support arm64 macs, CRAN has binaries for them: https://cran.rstudio.com/web/packages/filelock/

I am afraid you'll need to ask conda about its availability, we don't control that.

Btw. we also provide self-contained binaries for pak, do those not work for you? See at https://pak.r-lib.org/reference/install.html
